### PR TITLE
Fix parser for libraries

### LINKED ISSUE #223: Missing `newVersion` and `prevVersion` values
Hi! My [dependabot post workflow](https://github.com/swimmwatch/python-opendota/blob/master/.github/workflows/dependabot-post.yml) (It duplicates changes from `pyproject.toml` to mustache template `pyproject.toml`) ran `dependabot/fetch-metadata` action for getting `newVersion` and `prevVersion` values but they were empty ([workflow run link](https://github.com/swimmwatch/python-opendota/runs/7102405191?check_suite_focus=true)).

image

### PR DESCRIPTION
**Pull request by kachick**
Fixes #223

I have faced same issue.

In my case, most PRs have missing information except "github-actions" ecosystem.
Missing versions makes "outputs.update-type: null". It makes unexpected behavior of auto-merge.
https://github.com/dependabot/fetch-metadata/blob/a7c13a83a67acff9b107367e6e9f1cdf9a66e97f/README.md?plain=1#L134

Filled: https://github.com/kachick/ruby-ulid/pull/195 => https://github.com/kachick/ruby-ulid/runs/6909618923?check_suite_focus=true#step:2:18
Missing: https://github.com/kachick/ruby-ulid/pull/199 => https://github.com/kachick/ruby-ulid/runs/7083025063?check_suite_focus=true#step:2:18

They have different PR title. 

Following code sounds apply different commit message and title for library and applications.

https://github.com/dependabot/dependabot-core/blob/7444344c03b86112b4801eec92b0909e05dbfe33/common/lib/dependabot/pull_request_creator/message_builder.rb#L71-L110
https://github.com/dependabot/dependabot-core/blob/7444344c03b86112b4801eec92b0909e05dbfe33/common/lib/dependabot/pull_request_creator/message_builder.rb#L126-L130
https://github.com/dependabot/dependabot-core/blob/7444344c03b86112b4801eec92b0909e05dbfe33/common/lib/dependabot/pull_request_creator/message_builder.rb#L181-L216

However current parser targets only for application messages, it looks a cause to me.

### CODE REVIEW

**Comment by kachick** [comment]
Compared results
---

[Before](https://github.com/kachick/ruby-gem-template/actions/runs/3186140398/jobs/5196448027#step:2:14)

```
  outputs.dependency-names: test-unit
  outputs.dependency-type: direct:development
  outputs.update-type: null
  outputs.directory: /
  outputs.package-ecosystem: bundler
  outputs.target-branch: main
  outputs.previous-version: 
  outputs.new-version: 
  outputs.compatibility-score: 0
  outputs.alert-state: 
  outputs.ghsa-id: 
  outputs.cvss: 0
```

---
  
[After this PR](https://github.com/kachick/eqq/actions/runs/3186140373/jobs/5196447622#step:2:13)

```
  outputs.dependency-names: test-unit
  outputs.dependency-type: direct:development
  outputs.update-type: version-update:semver-patch
  outputs.directory: /
  outputs.package-ecosystem: bundler
  outputs.target-branch: main
  outputs.previous-version: 3.5.3
  outputs.new-version: 3.5.5
  
  outputs.compatibility-score: 0
  outputs.alert-state: 
  outputs.ghsa-id: 
  outputs.cvss: 0
```

**Comment by Nishnha** [comment]
Hi @kachick thanks for opening this PR!

I think this is off to a good start and I started the CI run 😄 

---

The indentation on this multiline string is a bit weird here
https://github.com/dependabot/fetch-metadata/blob/cf0e9797120828220f7be61d61514b9e293fd3a1/src/main.test.ts#L136-L148

Maybe we can treat each line as a separate string and join with `+` like in 
https://github.com/dependabot/fetch-metadata/blob/cf0e9797120828220f7be61d61514b9e293fd3a1/src/main.test.ts#L66-L79

What do you think?

**Comment by kachick** [comment]
@Nishnha

Thanks for your reviewing! I have updated this PR as https://github.com/dependabot/fetch-metadata/pull/224/commits/0a3f18375a9a1749a02dce2656df58200e195cfc. To keep same coding style with existing test cases.

**Review by Nishnha — APPROVED** [review]
This looks great! Thank you for being so patient

**Comment by Nishnha** [comment]
Released in https://github.com/dependabot/fetch-metadata/releases/tag/v1.3.6

**Comment by kachick** [comment]
Thank you!

**Pull request merged**
