### PR TITLE
Flag security alerts and pass versions through

### LINKED ISSUE #84: Flag security related dependabot PRs
Hi and thanks for this action.

I was wondering it the metadata had information about whether a PR raised by dependabot was due to a security alert/vulnerability.

Thanks.
Salim

### LINKED ISSUE #102: Pass version through metadata
We need a way to block pre-1.0.0 semver patch bumps.  Ideally, we'd have extra metadata available to us to allow us to easily do this via

`${{steps.metadata.outputs.version.major >= 1 && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}`

### PR DESCRIPTION
**Pull request by mwaddell**
closes #84 
closes #102

### CODE REVIEW

**Comment by mwaddell** [comment]
I still need to add test coverage to the new `getAlert` method which uses graphQL and update the documentation, but it's pretty close...

**Comment by mwaddell** [comment]
Updated documentation and addressed unit tests

**Review by brrygrdn — COMMENTED** [review]
This is awesome, thank you ❤️ 

I have one thought that might be a bit defensive. This is adds a call to the GitHub API that might be wasted if users don't care about these values - should we use an `input` flag, which defaults to `false` to ensure the query is only invoked when explicitly requested? 🤔 

I love this pattern of using the API to enrich the metadata further, but it might be worth setting a precedent of doing the least work by default.

**Comment by mwaddell** [comment]
> I have one thought that might be a bit defensive. This is adds a call to the GitHub API that might be wasted if users don't care about these values - should we use an `input` flag, which defaults to `false` to ensure the query is only invoked when explicitly requested? thinking
> 
> I love this pattern of using the API to enrich the metadata further, but it might be worth setting a precedent of doing the least work by default.

Yes, that makes perfect sense - I'll add that and assign it back for review

**Comment by mwaddell** [comment]
Done

**Review by brrygrdn — APPROVED** [review]
Thanks for this @mwaddell! I just want to do a minor release to get some house keeping updates out of the way and I'll get this merged 🚀

**Pull request merged**
