### PR TITLE
Adds several fields for alerts

### PR DESCRIPTION
**Pull request by timothy-humphrey**

### CODE REVIEW

**Comment by timothy-humphrey** [comment]
I need to update the ReadMe. My mistake.

**Comment by Nishnha** [comment]
Hi did you mean to bring this out of draft?

**Review by Rakhaau — APPROVED** [review]

**Comment by jeffwidman** [comment]
@timothy-humphrey this looks useful, anything I can do to help you get unblocked?

**Comment by honeyankit** [comment]
@timothy-humphrey: How can we unblock you on this task?

**Pull request closed without merging**
